export let serviceLibrary = [
    {
        "service-id": "primary-property-loan",
        "title": "Primary Property Loan",
        "img": "Images/house.jpeg",
        "our-service": "At E-W Global, we specialize in primary property programs, offering tailored solutions to help you secure the home of your dreams. Whether you're a first-time homebuyer or looking to upgrade to your forever home, our dedicated team is here to guide you through every step of the process.",
        "why-us-1": "With E-W Global, you can expect personalized service and attention to detail. We understand that buying a home is one of the most significant financial decisions you'll make, which is why we take the time to understand your unique needs and financial situation.",
        "why-us-2": "Our experienced professionals will work closely with you to explore all options, navigate the application process, and secure a plan that fits your budget and lifestyle. From competitive interest rates to flexible repayment terms, we offer a variety of plans designed to meet your specific needs. Whether you're looking for a conventional loan, FHA loan, VA loan, or USDA loan, we have the expertise and resources to help you find the right solution for your primary property.",
        "why-us-3": "With E-W Global, you can trust that you're in good hands. Contact us today to learn more about how our primary property program services can help you achieve your homeownership goals."
    }, {
        "service-id": "investment-property-loan",
        "title": "Investment Property Loan",
        "img": "Images/investment.jpg",
        "our-service": "At E-W Global, we specialize in investment property programs, providing customized solutions to help you grow your real estate portfolio. Whether you're a seasoned investor or just getting started, our dedicated team is here to assist you in navigating the complexities of investment property financing.",
        "why-us-1": "When it comes to investment property programs, we understand that every investor's goals and circumstances are unique. That's why we take the time to listen to your investment objectives and tailor our services to meet your specific needs. Whether you're looking to purchase a single-family home, a multi-unit property, or a commercial space, we have the expertise and resources to help you secure the financing you need.",
        "why-us-2": "With E-W Global, you can expect a seamless and transparent process from start to finish. Our experienced professionals will guide you through the application process, helping you understand your options and choose the programs that best aligns with your investment strategy. We offer competitive interest rates, flexible terms, and personalized service to ensure you meet your financial goals.",
        "why-us-3": "Whether you're looking to expand your rental property portfolio or venture into real estate investing for the first time, E-W Global is your trusted partner in achieving success. Contact us today to learn more about our investment property program services and discover how we can help you achieve your investment objectives."
    }, {
        "service-id": "commerical-property-loan",
        "title": "Commerical Property Loan",
        "img": "Images/Commercial.jpg",
        "our-service": "E-W Global specializes in commercial property programs, providing tailored financing solutions to support your business's real estate needs. Whether you're looking to purchase office space, retail storefronts, industrial warehouses, or any other type of commercial property, our experienced team is here to help you secure the funding you need to achieve your business goals.",
        "why-us-1": "Navigating the world of commercial property financing can be complex, but with E-W Global, you'll have a trusted partner by your side. We understand that every business is unique, which is why we take the time to understand your specific needs and objectives. Whether you're a small business owner or a seasoned investor, we'll work closely with you to customize a solution that fits your budget and long-term plans.",
        "why-us-2": "With E-W Global, you can expect personalized service and a commitment to excellence at every step of the process. Our dedicated professionals will guide you through the application process, helping you navigate the intricacies of commercial lending and ensuring that you have a clear understanding of your financing options. From competitive interest rates to flexible repayment terms, we offer a variety of loan products designed to meet the diverse needs of businesses of all sizes.",
        "why-us-3": "Unlock the potential of your business with a commercial property loan from E-W Global. Contact us today to learn more about our commercial lending services and discover how we can help you take your business to the next level."
    }, {
        "service-id": "hard-money-loan",
        "title": "Hard Money, Bridge Loans",
        "img": "Images/HardMoney.jpeg",
        "our-service": "E-W Global specializes in hard money bridge programs, offering swift and flexible financing solutions to address your short-term funding needs. Whether you're a real estate investor looking to seize opportunities quickly or a property owner in need of fast capital, our dedicated team is here to provide the financial support you require.",
        "why-us-1": "Hard money bridge programs are ideal for situations where traditional financing may not be readily available. With E-W Global, you can access the capital you need with minimal hassle and quick approval times. Our streamlined application process and efficient underwriting ensure that you receive the funds you need when you need them, allowing you to capitalize on time-sensitive opportunities without delay.",
        "why-us-2": "At E-W Global, we understand that every borrower's situation is unique. That's why we take a personalized approach to hard money bridge lending, working closely with you to understand your specific needs and objectives.",
        "why-us-3": "Whether you're looking to purchase distressed properties, renovate existing assets, or bridge the gap between property acquisitions, we'll customize a loan solution that aligns with your goals."
    }, {
        "service-id": "fix-flip-loan",
        "title": "Fix Flip Loans",
        "img": "Images/fix-flip.jpeg",
        "our-service": "E-W Global specializes in fix and flip programs, providing financing solutions tailored to real estate investors looking to purchase, renovate, and resell properties for profit. Whether you're a seasoned flipper or just getting started in the world of real estate investing, our dedicated team is here to help you secure the funding you need to execute your projects successfully.",
        "why-us-1": "Fix and flip loans are designed to provide investors with the capital required to acquire distressed properties, make necessary renovations, and ultimately sell the properties for a profit. At E-W Global, we understand the unique challenges and opportunities associated with fix and flip projects, which is why we offer flexible program terms and competitive rates to support your investment endeavors.",
        "why-us-2": "With E-W Global, you'll benefit from a streamlined loan process and personalized service every step of the way. Our experienced professionals will work closely with you to assess your project's scope and financial needs, ensuring that you receive the funding necessary to complete your fix and flip venture on time and within budget.",
        "why-us-3": "Unlock the potential of your fix and flip projects with E-W Global . Contact us today to learn more about our fix and flip options and discover how we can help you achieve your real estate investment goals with confidence."
    }, {
        "service-id": "construction-loan",
        "title": "Construction Loans",
        "img": "Images/construction-img.jpeg",
        "our-service": "E-W Global specializes in construction programs, offering financing solutions to support the building of new residential and commercial properties. Whether you're a developer embarking on a large-scale construction project or an individual building your dream home, our experienced team is here to provide the financial support and expertise you need to bring your vision to life.",
        "why-us-1": "Construction programs are unique in that they provide funding in stages as the project progresses. At E-W Global, we understand the complexities of construction financing and are committed to guiding you through the process with transparency and efficiency. From securing initial funding to managing disbursements throughout the construction phases, we'll work closely with you to ensure that your project stays on track and within budget.",
        "why-us-2": "With E-W Global, you can expect flexible program terms, competitive rates, and personalized service tailored to your specific needs. Our dedicated professionals will take the time to understand your project's scope, timeline, and budget requirements, helping you choose the right loan option to support your construction goals.",
        "why-us-3": "Experience the ease and convenience of construction financing with E-W Global. Contact us today to learn more about our construction loan options and discover how we can help you turn your construction dreams into reality with confidence."
    }, {
        "service-id": "foreign-loan",
        "title": "Foreign National Loans",
        "img": "Images/nation.jpeg",
        "our-service": "E-W Global specializes in foreign national programs, providing financing solutions for non-U.S. residents looking to invest in American real estate. Whether you're an international investor seeking opportunities in the U.S. market or a foreign national looking to purchase a vacation home, our dedicated team is here to assist you in navigating the complexities of cross-border lending.",
        "why-us-1": "Foreign national programs are designed to help non-U.S. citizens or residents secure financing for real estate investments in the United States. At E-W Global, we understand the unique challenges faced by international buyers, which is why we offer specialized  programs tailored to meet the needs of foreign nationals. From competitive interest rates to flexible repayment terms, we'll work closely with you to customize a loan solution that fits your unique circumstances.",
        "why-us-2": "With E-W Global, you can expect personalized service and support every step of the way. Our experienced professionals will guide you through the loan application process, helping you understand the documentation requirements and ensuring a smooth and efficient experience from start to finish. Whether you're purchasing a primary residence, an investment property, or a vacation home, we're here to help you achieve your real estate goals in the United States.",
        "why-us-3": "Unlock the potential of American real estate with E-W Global. Contact us today to learn more about our foreign national loan options and discover how we can help you invest in U.S. real estate with confidence."
    }, {
        "service-id": "land-loan",
        "title": "Land Loans",
        "img": "Images/land.jpeg",
        "our-service": "E-W Global specializes in land programs, offering financing solutions for individuals and developers looking to purchase vacant land for various purposes. Whether you're planning to build your dream home, develop a commercial property, or invest in land for future use, our experienced team is here to provide the financial support and expertise you need to make your land ownership goals a reality.",
        "why-us-1": "Land programs are unique in that they provide funding specifically for the purchase of vacant land, without any existing structures. At E-W Global, we understand the intricacies of land financing and are committed to guiding you through the process with clarity and efficiency. From securing initial funding to navigating zoning regulations and development plans, we'll work closely with you to ensure a smooth and seamless experience from start to finish.",
        "why-us-2": "With E-W Global, you can expect personalized service tailored to your specific needs and objectives. Our dedicated professionals will take the time to understand your vision for the land and customize a loan solution that aligns with your goals. Whether you're a first-time land buyer or an experienced developer, we're here to provide the support and expertise you need to succeed in your land ownership endeavors.",
        "why-us-3": "Unlock the potential of vacant land with E-W Global. Contact us today to learn more about our land loan options and discover how we can help you acquire and develop land with confidence."
    }, {
        "service-id": "sba-loan",
        "title": "SBA Loans",
        "img": "Images/sba.jpeg",
        "our-service": "E-W Global specializes in Small Business Administration (SBA) loans, offering financing solutions to support small businesses and entrepreneurs in achieving their goals. Whether you're looking to start a new business, expand your operations, or acquire commercial real estate, our dedicated team is here to provide the financial support and guidance you need to succeed.",
        "why-us-1": "SBA loans are backed by the U.S. Small Business Administration and are designed to help small businesses access affordable financing with favorable terms. At E-W Global, we understand the importance of SBA loans in fueling business growth and are committed to helping entrepreneurs navigate the SBA loan process with ease. From understanding eligibility requirements to preparing the necessary documentation, we'll work closely with you to ensure a smooth and efficient loan application process.",
        "why-us-2": "With E-W Global, you can expect personalized service tailored to your business needs. Our experienced professionals will take the time to understand your unique situation and customize an SBA loan solution that fits your specific goals and financial objectives.",
        "why-us-3": "Whether you're seeking working capital, financing for equipment purchases, or funds for real estate acquisitions, we're here to help you access the capital you need to thrive. Unlock the potential of your small business with an SBA loan from E-W Global. Contact us today to learn more about our SBA loan options and discover how we can help you achieve your business goals with confidence."
    }, {
        "service-id": "working-loan",
        "title": "Working Capital Loans",
        "img": "Images/capital.jpeg",
        "our-service": "E-W Global specializes in working capital programs, offering flexible financing solutions to support the ongoing operational needs of businesses. Whether you're looking to cover day-to-day expenses, invest in growth opportunities, or manage seasonal fluctuations, our dedicated team is here to provide the financial support you need to keep your business running smoothly.",
        "why-us-1": "Working capital loans are essential for businesses to maintain liquidity and meet short-term financial obligations. At E-W Global, we understand that access to timely funding is crucial for business success, which is why we offer fast and convenient working capital options designed to meet your specific needs. Whether you need funds to cover payroll, purchase inventory, or invest in marketing initiatives, we're here to help.",
        "why-us-2": "With E-W Global, you can expect a seamless and transparent loan process. Our experienced professionals will work closely with you to assess your working capital needs and customize a loan solution that aligns with your business objectives. From competitive interest rates to flexible repayment terms, we'll help you find the right financing option to support your business growth and stability.",
        "why-us-3": "Unlock the potential of your business with a working capital loan from E-W Global. Contact us today to learn more about our working capital loan options and discover how we can help you maintain financial stability and achieve your business goals with confidence."
    }, {
        "service-id": "equipment-loan",
        "title": "Equipment Loans",
        "img": "Images/equipment.jpeg",
        "our-service": "E-W Global specializes in equipment financing programs, providing tailored financing solutions to help businesses acquire the equipment they need to operate efficiently and effectively. Whether you're looking to upgrade your machinery, purchase new technology, or expand your fleet, our dedicated team is here to provide the financial support and expertise you need to make it happen.",
        "why-us-1": "Equipment loans are essential for businesses across various industries to acquire the necessary tools and machinery to remain competitive. At E-W Global, we understand the importance of having access to reliable equipment, which is why we offer flexible financing options designed to meet your specific needs. Whether you're a small business owner or a large corporation, we'll work closely with you to structure a loan solution that fits your budget and business goals.",
        "why-us-2": "With E-W Global, you can expect personalized service and support throughout the loan process. Our experienced professionals will take the time to understand your equipment needs and customize a financing solution that aligns with your objectives. From competitive interest rates to flexible repayment terms, we'll help you find the right loan option to acquire the equipment necessary to drive your business forward.",
        "why-us-3": "Unlock the potential of your business with an equipment loan from E-W Global. Contact us today to learn more about our equipment loan options and discover how we can help you acquire the tools and machinery you need to succeed with confidence."
    }
]